fs/ext4: Fix -Werror=restrict
error: 'snprintf' argument 4 overlaps destination object 'buf' [-Werror=restrict]
 2423 |   snprintf(buf, PAGE_SIZE, "%s\"%s\":\"%llu\",", buf, size[i],
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2424 |    (unsigned long long)freeblock[i]);

* Use scnprintf instead of snprintf

Signed-off-by: SamarV-121 <samarvispute121@gmail.com>